###
GET http://localhost:5000/api/tasks?size=7&title=plant

###
POST https://yaigenes.cat/api/tasks
Content-Type: application/json

{
  "title": "my love flavita",
  "description": "I love my baby",
  "done": true
}

###
GET http://localhost:5000/api/tasks/61b8986e4dd3a20c3a6c302b

###
DELETE https://yaigenes.cat/api/tasks/61bf9288e64a106963d0c50f

###
GET http://localhost:5000/api/tasks/done

###
PUT http://localhost:5000/api/tasks/61b89a2126dd91abe2e7b33f
Content-Type: application/json

{
  "description": "like a frog in the pond"
}