###
GET http://localhost:5000/api/tasks

###
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
  "title": "swim in the pool",
  "description": "take a dip and enjoy the water",
  "done": true
}

###
GET http://localhost:5000/api/tasks/61b8986e4dd3a20c3a6c302b

###
DELETE http://localhost:5000/api/tasks/61b8986e4dd3a20c3a6c302b

###
GET http://localhost:5000/api/tasks/done